src/main/java/com/tcvcog/tcvce/entities/EventCnF.java
/*  
 * Copyright (C) 2018 Turtle Creek Valley
Council of Governments, PA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tcvcog.tcvce.entities;

import com.tcvcog.tcvce.application.BackingBeanUtils;
import com.tcvcog.tcvce.application.interfaces.IFace_Loggable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;
import com.tcvcog.tcvce.util.Constants;
import com.tcvcog.tcvce.util.DateTimeUtil;
import java.time.LocalDate;
import java.time.ZoneOffset;
import com.tcvcog.tcvce.application.interfaces.IFaceActivatableBOB;
import com.tcvcog.tcvce.application.interfaces.IFaceCachable;

/**
 * Behold the base class of the EventCnF family!
 * @author ellen bascomb of apt 31y
 */
public  class       EventCnF 
        extends     TrackedEntity
        implements  Comparable<Object>,
                    IFace_Loggable,
                    IFace_noteHolder,
                    IFaceActivatableBOB,
                    IFace_humanListHolder,
                    IFace_PermissionsCreatorRightsPreserved,
                    IFace_EventLinked,
                    IFaceCachable{
    
    final static LinkedObjectSchemaEnum HUMAN_LINK_SCHEMA_ENUM = LinkedObjectSchemaEnum.EventHuman;
    final static String EVENT_FRIENDLY_NAME = "Event";
    final static String EVENT_TABLE_NAME = "event";
    final static String EVENT_PK_FIELD = "eventid";
    
    protected int eventID;
    protected EventCategory category;
    protected String description;
    
    
    protected List<HumanLink> humanLinkList;
    
    /**
     * Indicates to clients which BOb identifier to use
     * Alternatively, one could have only one field for the ID
     * and use Domain to control what we do with that ID
     * But that seemed to likely lead to more confusion since the DB
     * has two columns, since each is keyed differently
     */
    protected EventRealm domain;
    
    //Events can be attached to one of these three parent objects. If more than
    // one of these three is NON zero then we have a configuration error--a major one!
    protected int ceCaseID;
    protected int occPeriodID;
    protected int parcelKey;
    
    protected List<EventCnF> eventList;
    
    // flattened fields for showing event relationships without
    // cycle risk
    protected String parcelAddressTwoLineEscapeFalse;
    protected String parcelAddressOneLine;
    protected String caseName;
    protected String propertyUnitNumber;
    protected String casePeriodPropertyString;
    
    protected LocalDateTime timeStart;
    protected LocalDateTime timeEnd;
    
    protected boolean active;
    protected String notes;
    
    /**
     * Only for use in JavaLand; no DB col for hiding
     */
    protected boolean hidden;
    protected long duration;
    
    
    public EventCnF(){
        
        
    }
    
    public EventCnF(EventCnF ev){
        
        this.eventID = ev.eventID;
        this.category = ev.category;
        this.description = ev.description;
        
        this.domain = ev.domain;
        this.ceCaseID = ev.ceCaseID;
        this.occPeriodID = ev.occPeriodID;
        
        this.parcelAddressTwoLineEscapeFalse = ev.parcelAddressTwoLineEscapeFalse;
        this.parcelAddressOneLine = ev.parcelAddressOneLine;
        this.casePeriodPropertyString = ev.casePeriodPropertyString;
        
        this.timeStart = ev.timeStart;
        this.timeEnd = ev.timeEnd;
        
        this.active = ev.active;

        this.hidden = ev.hidden;
        this.notes = ev.notes;
        
        this.createdBy = ev.createdBy;
        this.createdTS = ev.createdTS;

        this.lastUpdatedBy = ev.lastUpdatedBy;
        this.lastUpdatedTS = ev.lastUpdatedTS;

        this.deactivatedBy = ev.deactivatedBy;
        this.deactivatedTS = ev.deactivatedTS;
    }
    
    /**
     * Mini logic block for determining if this event requires follow up and
     * as of last instantiation, has not had such follow up.
     * 
     * @return 
     */
    public boolean isFollowUpNeeded(){
       if(category != null && category.isFollowUpEvent()){
            if(eventList == null){
                return true;
            } else {
                if(eventList.isEmpty()){
                    return true;
                }
            }
        } 
       return false;
    }
    
    /**
     * Convenience method for adding to an event's description 
     * without having to manage what's already in the field.
     * Just send me a String and I'll slap it on the end of the
     * existing description.
     * @param textToAppend 
     */
    public void appendToDescription(String textToAppend){
        if(textToAppend != null){
            StringBuilder sb = new StringBuilder();
            if(Objects.nonNull(description) && !description.equals("") && !description.equals(" ")){
                sb.append(description);
                sb.append(Constants.FMT_SEMICOLON);
                sb.append(Constants.FMT_SPACE_LITERAL);
            }
            sb.append(textToAppend);
            description = sb.toString();
        }
    }
    
    /**
     * Takes in a start time and will set the end time based on either the given
     * nonzero duration or the cat's default duration
     * 
     * @param start the event's start time
     * @param durationMins if not 0, i'll override the cat default duration
     */
    public void configureEventTimesFromStartTime(LocalDateTime start, int durationMins){
       if(start != null){
           timeStart = start;
           if(durationMins != 0){
                timeEnd = timeStart.plusMinutes(durationMins);
           } else if(category != null){
                timeEnd = timeStart.plusMinutes(category.getDefaultDurationMins());
           }
           if(timeStart != null && timeEnd != null){
                System.out.println("EventCnF.ConfigureEventTimesFromStartTime | start time: " + timeStart.toString());
                System.out.println("EventCnF.ConfigureEventTimesFromStartTime | New end time: " + timeEnd.toString());
           }
       } 
    }
    
    /**
     * Extracts ONLY the date portion of the event start time for table sorting.
     * @return 
     */
    public LocalDate getEventStartDateOnly(){
        if(timeStart != null){
            return timeStart.toLocalDate();
        }
        else {
            return null;
        }
    }
    
    /**
     * Convenience method for returning the non-zero id in the set of parent
     * key fields: case, period, and property
     * @return the parent key, or -9 for all zero parent keys
     */
    public int getParentID(){
        if(ceCaseID != 0){
            return ceCaseID;
        }
        if(parcelKey != 0){
            return parcelKey;
        }
        if(occPeriodID != 0){
            return occPeriodID;
        }
        return -9;
    }
    
    /**
     * @return the eventID
     */
    public int getEventID() {
        return eventID;
    }

    /**
     * @return the category
     */
    public EventCategory getCategory() {
        return category;
    }

   
    /**
     * Gets the description
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Special: I read for the presence of deac ts
     * @return the active
     */
    @Override
    public boolean isActive() {
        return deactivatedTS == null;
    }

    /**
     * @return the hidden
     */
    public boolean isHidden() {
        return hidden;
    }

    /**
     * @return the notes
     */
    @Override
    public String getNotes() {
        return notes;
    }

    /**
     * @param eventID the eventID to set
     */
    public void setEventID(int eventID) {
        this.eventID = eventID;
    }

    /**
     * @param category the category to set
     */
    public void setCategory(EventCategory category) {
        this.category = category;
    }



    /**
     * Do not use me: use appendToDescription(String s) instead
     * so as to not disturb existing content
     * @Deprecated 
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }


   
    /**
     * @param active the active to set
     */
    public void setActive(boolean active) {
        this.active = active;
    }

    /**
     * @param hidden the hidden to set
     */
    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }

    /**
     * @param notes the notes to set
     */
    @Override
    public void setNotes(String notes) {
        this.notes = notes;
    }

  
    @Override
    public int compareTo(Object e) {
        if(Objects.isNull(e)){
            throw new NullPointerException("Cannot compare null events");
        }
        if(!(e instanceof EventCnF)){
            throw new ClassCastException("Cannot cast incoming object to EventCnF");
        }
        EventCnF inEv = (EventCnF) e;
        int c = 0;
        if(this.timeStart != null && inEv.timeStart != null){
            Long thisEpoch = this.timeStart.toEpochSecond(ZoneOffset.UTC);
            Long incomingEpoch = inEv.getTimeStart().toEpochSecond(ZoneOffset.UTC);
            c = thisEpoch.compareTo(incomingEpoch);
        } else if(this.createdTS != null && inEv.createdTS != null){

src/main/java/com/tcvcog/tcvce/entities/EventType.java
    /*
 * Copyright (C) 2018 Turtle Creek Valley
Council of Governments, PA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tcvcog.tcvce.entities;

/**
 * Represents a top-level grouping of EventCategory objects
 * @author ellen bascomb of apt 31y
 */
public enum EventType {
    Accounting("money-related", 3, 2),
    Action("Officer Action", 5, 1),
    CaseAdmin("Case Admin", 3, 2),
    Citation("Citation", 5, 3),
    
    Casereopen("Case Reopening", 5, 1),
    Closing("Case Closing", 5, 1),
    Origination("Case Origination", 5, 1),
    Communication("Communication", 5, 2),
    Violation("Violation", 5, 3),
    Court("Court-related", 3, 1), // probably don't need this one AND citation
    
    Custom("Custom", 3, 1),
    Inspection("Inspection related", 3, 1),
    Meeting("Meeting", 3, 1),
    Notice("Notice", 3, 1),
    
    Occupancy("Occupancy", 5, 3),
    OccupancyOrigination("Permit file origination", 3, 1),
    OccupancyClosing("Permit file closing", 3, 1),
    
    PhaseChange("Case Phase Change", 5, 1),
    Timeline("Case Timeline", 4, 1),
    Workflow("Workflow", 5, 1),
    
    PropertyInfoCase("Property Info", 3, 1),
    PropertyAlert("Property alerts", 2, 1);

    private final String label;
    protected final int userRankMinimumToEnact;
    protected final int userRankMinimumToView;

    private EventType(String label, int enactMin, int viewMin) {
        this.label = label;
        this.userRankMinimumToEnact = enactMin;
        this.userRankMinimumToView = viewMin;
    }

    public String getLabel() {
        return label;
    }

    /**
     * @return the userRankMinimumToEnact
     */
    public int getUserRankMinimumToEnact() {
        return userRankMinimumToEnact;
    }

    /**
     * @return the userRankMinimumToView
     */
    public int getUserRankMinimumToView() {
        return userRankMinimumToView;
    }
    
        
    
    
}

src/main/webapp/restricted/cogstaff/event/compositions/eventListPanel.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:tt="http://xmlns.jcp.org/jsf/composite/components">

    <p:panel id="events-panel"
             toggleable="true"
             collapsed="false">

        <f:facet name="header">
            <h:form id="event-panel-header-form">
                <h:outputText value="Events attached to #{eventBB.currentEventHolder.eventDomain.title} (ID:#{eventBB.currentEventHolder.BObID})" />
                <div class="restrict-main-contents-io-link link-button help-icon-tightright">
                    <a href="https://technologyrediscovery.github.io/codenforce/case/casescreen#log-an-event"
                       target="_blank">
                        <i class="material-icons"
                           style="display: inline-block">help_outline</i>
                    </a>
                </div>
                <div class="restrict-main-contents-io-link link-button help-text-tightleft">
                    <a href="https://technologyrediscovery.github.io/codenforce/case/casescreen#log-an-event"
                       target="_blank">
                        <h:outputText value="help" />
                    </a>
                </div>
            </h:form>
        </f:facet>

        <h:form id="event-masterlist-form">

            <p:commandButton id="events-add-button"
                             styleClass="noFill button-size-small"
                             value="Add Event"
                             icon="pi pi-plus"
                             rendered="#{systemServicesBB.permissionAllowAncillaryObjectEdit}"
                             disabled="#{sessionBean.crossMuniViewMode}"
                             actionListener="#{eventBB.onEventAddInit}"
                             oncomplete="PF('event-add-dialog-var').show()"
                             update="event-add-dialog"
                             >

                <f:param name="event-list-component-to-update" 
                         value="event-masterlist-form" />

            </p:commandButton>

            <p:commandLink value="Export events to calendar"
                           action="#{eventBB.changeSelectionMode()}"
                           update="@form"
                           style="color: blue; margin-left: 5px; font-weight: bold"/>

            <p:spacer height="5px"/>
            
            <p:dataTable id="crossdomain-events-table"
                         value="#{eventBB.managedEventList}"
                         rendered="true"
                         var="genevent"
                         tableStyleClass="primeDataTable"
                         rowKey="#{genevent.eventID}"
                         reflow="true"
                         selection="#{eventBB.selectedEvents}"
                         rowStyleClass="#{genevent.followUpNeeded ? 'followup':''}"
                         selectionMode="multiple" 
                         >

                <p:column 
                          styleClass="centeredColumnContent" 
                          style="width:16px;text-align:center" 
                          rendered="#{eventBB.selectionMode}"/>

                <p:column headerText="Date"
                          width="20%"
                          sortBy="#{genevent.eventStartDateOnly}"
                          styleClass="centeredColumnContent">
                    <h:outputText value="#{empty genevent.timeStart ? eventBB.getPrettyDate(genevent.createdTS) : eventBB.getPrettyDate(genevent.timeStart) }"/>
                </p:column>

                <p:column headerText="Category"
                          width="20%"
                          sortBy="#{genevent.category.eventCategoryTitle}"
                          styleClass="centeredColumnContent #{genevent.category.alertEvent ? 'alert-background':''}">

                    <div class="#{genevent.category.icon.styleClass}">
                        <i class="material-icons status-display-icon-i"><h:outputText value="#{genevent.category.icon.materialIcon}"/></i>
                    </div>

                    <h:outputText value="#{genevent.category.eventType.label}:"
                                  styleClass="#{genevent.category.alertEvent ? 'bold':''}"/>

                    <p:spacer height="1px" />

                    <h:outputText value="#{genevent.category.eventCategoryTitle}"
                                  styleClass="#{genevent.category.alertEvent ? 'bold':''}"/>
                    <p:spacer height="1px" />
                    <h:outputText value="Property Alert!"
                                  rendered="#{genevent.category.alertEvent}"
                                  styleClass="#{genevent.category.alertEvent ? 'bold':''}"/>
                </p:column>

                <p:column headerText="Description"
                          width="50%"
                          styleClass="wrapText">

                    <h:outputText value="#{genevent.description}"
                                  escape="false"/>
                    <p:spacer height="3px" />
                    <h:outputText value="(OPID:#{genevent.occPeriodID}) (PCLID: #{genevent.parcelKey}) (CSEID:#{genevent.ceCaseID})"
                                  rendered="false" />


                </p:column>

                <p:column headerText="Actions"
                          width="10%"
                          styleClass="centeredColumnContent"
                          sortBy="#{genevent.eventID}">
                    <div class="restrict-main-contents-io-link link-button">
                        <p:commandLink id="event-open-button"
                                       styleClass="noFill button-size-small"
                                       value="view/edit"
                                       rendered="#{not sessionBean.crossMuniViewMode}"
                                       type="button"
                                       ajax="true"
                                       oncomplete="PF('event-profile-dialog-var').show()"
                                       update="event-profile-dialog
                                       event-profile-form"
                                       >
                            <p:ajax listener="#{eventBB.onViewEvent(genevent)}" />
                            <f:param name="event-list-component-to-update" 
                                     value="event-masterlist-form:crossdomain-events-table" />
                        </p:commandLink>
                    </div>

                    <f:subview id="case-event-followup-required-subview"
                               rendered="#{genevent.followUpNeeded}">
                        <p:spacer height="3px" />
                        <div class="restrict-main-contents-io-link event-followup-required">
                            <p:commandLink id="event-masterlist-followup-cl"
                                           actionListener="#{eventBB.onFollowUpToEventInit(genevent)}"
                                           oncomplete="PF('event-add-dialog-var').show()"
                                           update="event-add-dialog">
                                <f:param name="event-list-component-to-update" value="event-masterlist-form:crossdomain-events-table" />
                                <h:outputText value="Follow up" />
                            </p:commandLink>
                        </div>
                    </f:subview>

                    <f:subview id="event-masterlist-followup-satisfied-subview"
                               rendered="#{not genevent.followUpNeeded and genevent.category.followUpEvent}">
                        <p:spacer height="3px" />
                        <div class="p-grid">
                            <div class="p-col-2">
                                <div class="evcal-evicon-container">
                                    <i class="material-icons">
                                        <h:outputText value="done"/>
                                    </i>
                                </div>
                            </div>

                            <div class="p-col-10">
                                <h:outputText value="Follow-up complete!"/>
                            </div>
                        </div>
                    </f:subview>

                    <p:spacer height="3px" />
                    <h:outputText value="(ID:#{genevent.eventID})"/>
                    
                    <p:spacer height="3px" />
                    <h:outputText value="#{empty genevent.deactivatedTS ? 'Active' : 'Deactivated'}"
                                  styleClass="italic"/>

                </p:column>
            </p:dataTable>
            <p:spacer height="5px"/>

            <p:commandButton styleClass="noFill button-size-small" 
                             value="Export Selected Events To Calendar File" 
                             icon="pi pi-download"
                             action="#{eventBB.exportCalendar()}" 
                             ajax="false" 
                             rendered="#{eventBB.selectionMode}" 
                             />
            <p:commandButton styleClass="noFill button-size-small ui-button-secondary" 
                             value="Done/Cancel" 
                             icon="pi pi-thumbs-up"
                             style="margin-left: 5px" 
                             rendered="#{eventBB.selectionMode}" 
                             action="#{eventBB.abortExportOperation()}" 
                             update="@form"/>
        </h:form>
    </p:panel>


</ui:composition>

src/main/webapp/restricted/cogstaff/event/compositions/propertyAlertFlags.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:tt="http://xmlns.jcp.org/jsf/composite/components">

    <f:subview id="propertyalerts-subview"
               rendered="#{sessionBean.sessProperty.propertyAlerts.renderAlerts}">
        <h:form id="alerts-form">
            <div class="alert-container"
                 style="width:100%">

                <div class="p-grid alert-background">

                    <ui:repeat id="alert-uir"
                               value="#{sessionBean.sessProperty.propertyAlerts.alertsActive}"
                               var="alert">
                        <div class="p-col-1 alert-text">
                            <i class="material-icons">
                                <h:outputText value="#{alert.alertEvent.category.icon.materialIcon}" />
                            </i>
                        </div>
                        <div class="p-col-7 alert-text">
                            <h:outputText value="#{alert.alertEvent.category.eventCategoryTitle}" />
                        </div>
                        <ui:include src="propertyAlertManageCols.xhtml" />
                    </ui:repeat>
                </div>
            </div>
        </h:form>
    </f:subview>
</ui:composition>

src/main/webapp/restricted/cogstaff/event/compositions/propertyAlertManageCols.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:tt="http://xmlns.jcp.org/jsf/composite/components">
    <f:subview id="alert-action-cols"
               rendered="#{sessionBean.propertyPageFocus}">


        <div class="p-col-2">
            <div class="restrict-main-contents-io-link" >

                <p:commandLink id="alert-event-details-cl"
                               value="details"
                               ajax="true"
                               oncomplete="PF('event-profile-dialog-var').show()"
                               update=" event-profile-dialog 
                               event-profile-form"
                               actionListener="#{eventBB.onViewEvent(alert.alertEvent)}">
                </p:commandLink>

            </div>
        </div>
        <div class="p-col-2">
            <div class="restrict-main-contents-io-link" >

                <p:commandLink id="alert-stop-init-cl"
                               value="stop this alert"
                               ajax="true"
                               actionListener="#{eventBB.onStopALertEventInit(alert.alertEvent)}"
                               oncomplete="PF('event-add-dialog-var').show()"
                               update="event-add-dialog" >
                <f:param name="event-list-component-to-update" 
                         value="event-masterlist-form" />

                </p:commandLink>
            </div>
        </div>
    </f:subview>
    <f:subview id="no-actions-fillers-cols"
               rendered="#{not sessionBean.propertyPageFocus}">


        <div class="p-col-2">
            <h:outputText value=" " />
        </div>
        <div class="p-col-2">
            <h:outputText value=" " />
        </div>
    </f:subview>

</ui:composition>