src/main/java/com/tcvcog/tcvce/entities/CitationPenalty.java
/*
 * Copyright (C) 2024 pierre15
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tcvcog.tcvce.entities;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Embodies a penalty imposed on a violation or at the citation level
 * @author pierre15
 */
public class CitationPenalty extends TrackedEntity{
    static String PENALTY_PK = "penaltyid";
    static String PENALTY_TABLE = "citationpenalty";
    
    private int penaltyID;
    private CitationPenaltyTypeEnum penaltyType;
    private BigDecimal fineAmount;
    private int jailDays;
    private String notes;
    private LocalDate dateOfRecord;
    private int citationID;
    private int citationViolationID;

    @Override
    public String getPKFieldName() {
        return PENALTY_PK;
    }

    @Override
    public int getDBKey() {
        return penaltyID;
    }

    @Override
    public String getDBTableName() {
        return PENALTY_TABLE;
    }

    /**
     * @return the PENALTY_PK
     */
    public static String getPENALTY_PK() {
        return PENALTY_PK;
    }

    /**
     * @param aPENALTY_PK the PENALTY_PK to set
     */
    public static void setPENALTY_PK(String aPENALTY_PK) {
        PENALTY_PK = aPENALTY_PK;
    }

    /**
     * @return the PENALTY_TABLE
     */
    public static String getPENALTY_TABLE() {
        return PENALTY_TABLE;
    }

    /**
     * @param aPENALTY_TABLE the PENALTY_TABLE to set
     */
    public static void setPENALTY_TABLE(String aPENALTY_TABLE) {
        PENALTY_TABLE = aPENALTY_TABLE;
    }

    /**
     * @return the penaltyID
     */
    public int getPenaltyID() {
        return penaltyID;
    }

    /**
     * @param penaltyID the penaltyID to set
     */
    public void setPenaltyID(int penaltyID) {
        this.penaltyID = penaltyID;
    }

    /**
     * @return the penaltyType
     */
    public CitationPenaltyTypeEnum getPenaltyType() {
        return penaltyType;
    }

    /**
     * @param penaltyType the penaltyType to set
     */
    public void setPenaltyType(CitationPenaltyTypeEnum penaltyType) {
        this.penaltyType = penaltyType;
    }

    /**
     * @return the fineAmount
     */
    public BigDecimal getFineAmount() {
        return fineAmount;
    }

    /**
     * @param fineAmount the fineAmount to set
     */
    public void setFineAmount(BigDecimal fineAmount) {
        this.fineAmount = fineAmount;
    }

    /**
     * @return the jailDays
     */
    public int getJailDays() {
        return jailDays;
    }

    /**
     * @param jailDays the jailDays to set
     */
    public void setJailDays(int jailDays) {
        this.jailDays = jailDays;
    }

    /**
     * @return the notes
     */
    public String getNotes() {
        return notes;
    }

    /**
     * @param notes the notes to set
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * @return the dateOfRecord
     */
    public LocalDate getDateOfRecord() {
        return dateOfRecord;
    }

    /**
     * @param dateOfRecord the dateOfRecord to set
     */
    public void setDateOfRecord(LocalDate dateOfRecord) {
        this.dateOfRecord = dateOfRecord;
    }

    /**
     * @return the citationID
     */
    public int getCitationID() {
        return citationID;
    }

    /**
     * @param citationID the citationID to set
     */
    public void setCitationID(int citationID) {
        this.citationID = citationID;
    }

    /**
     * @return the citationViolationID
     */
    public int getCitationViolationID() {
        return citationViolationID;
    }

    /**
     * @param citationViolationID the citationViolationID to set
     */
    public void setCitationViolationID(int citationViolationID) {
        this.citationViolationID = citationViolationID;
    }
    
    
    
}

src/main/java/com/tcvcog/tcvce/entities/User.java
/*
 * Copyright (C) 2017 cedba
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.tcvcog.tcvce.entities;

import com.tcvcog.tcvce.application.interfaces.IFaceCachable;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

/**
 * Our base class for a system User. Note a User doesn't have 
 * any credentials to do anything only to hold information. 
 * See UserAuthorized for the credentialed subclass.
 * @author cedba
 */
public class User 
        implements Serializable, IFaceCachable{

    protected int userID;
    protected String username;
    
    protected Human userHuman;
    private int humanID;
    
    protected String notes;
 
    protected boolean noLoginVirtualUser;
    
    protected int createdByUserId;
    protected LocalDateTime createdTS;
    private int lastUpdatedByUserID;
    protected LocalDateTime lastUpdatedTS;
    
    protected LocalDateTime deactivatedTS;
    protected int deactivatedByUserID;
    
    protected int homeMuniID;
    protected int signatureBlobID;
    
    protected LocalDateTime forcePasswordResetTS;
    protected int forcedPasswordResetByUserID;
    
    
    
    
    
    /**
     * Creates a new instance of User
     */
    public User() {
    }
    
    
    public User(User u){
      if(u != null){
            
            this.userID = u.getUserID();
            this.username = u.getUsername();
            
            this.userHuman = u.getHuman();
            this.humanID = u.getHumanID();
            
            this.notes = u.getNotes();

            this.noLoginVirtualUser = u.isNoLoginVirtualUser();

            this.createdByUserId = u.getCreatedByUserId();
            this.createdTS = u.getCreatedTS();

            this.deactivatedByUserID = u.deactivatedByUserID;
            this.lastUpdatedTS = u.lastUpdatedTS;
            
            this.deactivatedTS = u.deactivatedTS;
            this.deactivatedByUserID = u.deactivatedByUserID;
            
            this.homeMuniID = u.homeMuniID;
            this.signatureBlobID = u.signatureBlobID;
            
            this.forcePasswordResetTS = u.getForcePasswordResetTS();
            this.forcedPasswordResetByUserID = u.getForcedPasswordResetByUserID();
          
        }
    }
    
  
    /**
     * Special getter that will return this object's 
     * userHuman object's ID if its not null
     * @return the humanID
     */
    public int getHumanID() {
        if(this.userHuman != null){
            return userHuman.getHumanID();
        }
        return humanID;
    }

    
    public Human getUserHuman(){
        return this.userHuman;
    }
    
    
    public void setUserID(int uid){
        userID = uid;
    }

    /**
     * @return the userID
     */
    public int getUserID() {
        return userID;
    }

   
    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    
   
    /**
     * @return the notes
     */
    public String getNotes() {
        return notes;
    }

    /**
     * @param notes the notes to set
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
    // no setters for access permissions private variables!!
    /**
     * @return the keyCard
     */
    /**
     * @param keyCard the keyCard to set
     */   
    
    
    /**
     * adaptor for the userHuman member
     * @return the userHuman
     */
    public Human getHuman() {
        return userHuman;
    }

    /**
     * @param hum the userHuman to set - It's actually a Human, not an 
 Instance of Person class
     */
    public void setUserHuman(Human hum) {
        if(hum != null){
            humanID = hum.getHumanID();
        }
        this.userHuman = hum;
    }


   
    


  

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 43 * hash + this.userID;
        hash = 43 * hash + Objects.hashCode(this.username);
        hash = 43 * hash + Objects.hashCode(this.userHuman);
        hash = 43 * hash + this.getHumanID();
        hash = 43 * hash + Objects.hashCode(this.notes);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final User other = (User) obj;
        return this.userID == other.userID;
    }

    /**
     * @return the pswdLastUpdated
     */

    /**
     * @return the active
     */
    public boolean isActive() {
        boolean active = true;
        if(deactivatedTS != null){
            active = false;
        }
        return active;
    }

    /**
     * @return the noLoginVirtualUser
     */
    public boolean isNoLoginVirtualUser() {
        return noLoginVirtualUser;
    }


    /**
     * @param noLoginVirtualUser the noLoginVirtualUser to set
     */
    public void setNoLoginVirtualUser(boolean noLoginVirtualUser) {
        this.noLoginVirtualUser = noLoginVirtualUser;
    }

    /**
     * @return the createdByUserId
     */
    public int getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * @return the createdTS
     */
    public LocalDateTime getCreatedTS() {
        return createdTS;
    }

    /**
     * @return the pswdLastUpdated
     */
    /**
     * @param createdByUserId the createdByUserId to set
     */
    public void setCreatedByUserId(int createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * @param createdTS the createdTS to set
     */
    public void setCreatedTS(LocalDateTime createdTS) {
        this.createdTS = createdTS;
    }

    /**
     * @return the deactivatedTS
     */
    public LocalDateTime getDeactivatedTS() {
        return deactivatedTS;
    }

    /**
     * @return the deactivatedByUserID
     */
    public int getDeactivatedByUserID() {
        return deactivatedByUserID;
    }

    /**
     * @param deactivatedTS the deactivatedTS to set
     */
    public void setDeactivatedTS(LocalDateTime deactivatedTS) {
        this.deactivatedTS = deactivatedTS;
    }

    /**
     * @param userid
     */
    public void setDeactivatedByUserID(int userid) {
        this.deactivatedByUserID =userid;
    }

    /**
     * @return the lastUpdatedTS
     */
    public LocalDateTime getLastUpdatedTS() {
        return lastUpdatedTS;
    }

    /**
     * @param lastUpdatedTS the lastUpdatedTS to set
     */
    public void setLastUpdatedTS(LocalDateTime lastUpdatedTS) {
        this.lastUpdatedTS = lastUpdatedTS;
    }

    /**
     * @return the homeMuniID
     */
    public int getHomeMuniID() {
        return homeMuniID;
    }

    /**
     * @param homeMuniID the homeMuniID to set
     */
    public void setHomeMuniID(int homeMuniID) {
        this.homeMuniID = homeMuniID;
    }

    /**
     * @return the lastUpdatedByUserID
     */
    public int getLastUpdatedByUserID() {
        return lastUpdatedByUserID;
    }

    /**
     * @param lastUpdatedByUserID the lastUpdatedByUserID to set
     */
    public void setLastUpdatedByUserID(int lastUpdatedByUserID) {
        this.lastUpdatedByUserID = lastUpdatedByUserID;
    }

    /**
     * @param humanID the humanID to set
     */
    public void setHumanID(int humanID) {
        this.humanID = humanID;
    }

    /**
     * @return the signatureBlobID
     */
    public int getSignatureBlobID() {
        return signatureBlobID;
    }

    /**
     * @param signatureBlobID the signatureBlobID to set
     */
    public void setSignatureBlobID(int signatureBlobID) {
        this.signatureBlobID = signatureBlobID;
    }

    /**
     * @return the forcePasswordResetTS
     */
    public LocalDateTime getForcePasswordResetTS() {
        return forcePasswordResetTS;
    }

    /**
     * @return the forcedPasswordResetByUserID
     */
    public int getForcedPasswordResetByUserID() {
        return forcedPasswordResetByUserID;
    }

    /**
     * @param forcePasswordResetTS the forcePasswordResetTS to set
     */
    public void setForcePasswordResetTS(LocalDateTime forcePasswordResetTS) {
        this.forcePasswordResetTS = forcePasswordResetTS;
    }

    /**
     * @param forcedPasswordResetByUserID the forcedPasswordResetByUserID to set
     */
    public void setForcedPasswordResetByUserID(int forcedPasswordResetByUserID) {
        this.forcedPasswordResetByUserID = forcedPasswordResetByUserID;
    }

    @Override
    public int getCacheKey() {
        return userID;
    }

   
  

}

src/main/webapp/resources/components/caseAddCC.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <cc:interface>
        <cc:attribute name="containingformpath" required="true" type="java.lang.String" />
        <cc:attribute name="addfrompropertyprofile" required="true" type="boolean"/>
        <cc:attribute name="addfromfinrouting" required="true" type="boolean"/>
        <cc:attribute name="addfromcearrouting" required="true" type="boolean"/>
    </cc:interface>

    <cc:implementation>

        
        <h:outputText value="Create case at #{sessionBean.sessProperty.address.addressPretty1Line}, Parcel ID: #{sessionBean.sessProperty.countyParcelID}" />
        <div class="p-grid">
            <div class="p-col-4">
                <h:outputLabel value="Case Name" 
                               for="caseNameIT"/>
                <p:commandButton id="casename-help-button"
                                 icon="pi pi-question-circle"
                                 styleClass="button-help"
                                 type="button" />

                <p:overlayPanel for="casename-help-button"
                                style="width:350px;" 
                                dismissable="true"
                                showCloseIcon="true">
                    <h3>Code enforcement case names</h3>
                    <p>A case's name is a text field for INTERNAL office use only that allows managers to label a case something memorable,
                        such as 'deer feeding lady' or 'fridge in front yard' or 'imploded garage'. The case name appears on the dashboard's
                        case list for easy ID but does not by default print on case list reports .</p>
                </p:overlayPanel>

            </div>
            <div class="p-col-8">
                <p:inputText    id="caseNameIT" 
                                value="#{ceCaseAddBB.currentCECase.caseName}" 
                                style="width: 100%;" 
                                tabindex="1" 
                                required="false" />
            </div>

            <div class="p-col-4">
                <h:outputLabel value="Case Opening Date" 
                               for="formOpenDateCal"/>
            </div>
            <div class="p-col-8">
                <p:datePicker       value="#{ceCaseAddBB.currentCECase.originationDate}" 
                                    id="cecase-add-origdate-picker"
                                    showButtonBar="true"
                                    monthNavigator="true"
                                    timeInput="true"
                                    yearNavigator="true"
                                    hideOnDateTimeSelect="true"
                                    showOnFocus="false"
                                    showIcon="true"
                                    mask="false"
                                    tabindex="16" >

                </p:datePicker>
            </div>
            <div class="p-col-4">
                <h:outputLabel value="Case manager" />
            </div>
            <div class="p-col-8">
                <h:outputText rendered="true"
                              value="#{ceCaseAddBB.currentCECase.caseManager.human.name}"/>
                <p:spacer height="3px" />
                <div class="restrict-main-contents-io-link">

                    <p:commandLink  id="cecaseadd-changemanager-init-cl"
                                    value="edit manager"
                                    ajax="true"
                                    actionListener="#{ceCaseAddBB.onChangeManagerInit}"
                                    oncomplete="PF('cecaseadd-changemanager-dialog-var').show();"
                                    update="cecaseadd-changemanager-form">
                        <f:param name="cecase-add-containing-form" value="#{cc.attrs.containingformpath}" />
                    </p:commandLink>
                </div>

            </div>
            <div class="p-col-4">
                <h:outputLabel value="Origination category" 
                               for="cecase-add-origevent-som"/>

                <p:commandButton id="case-originationevent-help-button"
                                 icon="pi pi-question-circle"
                                 styleClass="button-help"
                                 type="button" />

                <p:overlayPanel for="case-originationevent-help-button"
                                style="width:350px;" 
                                dismissable="true"
                                showCloseIcon="true">
                    <h3>Origination events</h3>
                    <p>An origination event is automatically attached to a code enforcement case to signal 
                        where the case came from, such as resulting from an officer's routine patrol or from
                        a lapsed occupancy permit inspection with outstanding violation.</p>

                    <p>By selecting an accurate event category from this list now, 
                        the case's even history will be accurate from the beginning.</p>
                </p:overlayPanel>

            </div>
            <div class="p-col-8">
                <h:selectOneMenu id="cecase-add-origevent-som"
                                 value="#{ceCaseAddBB.currentCECase.originationEventCategory}"
                                 required="true">

                    <f:converter converterId="eventCategoryConverter"/>
                    <f:selectItem itemLabel="select an event category"
                                  noSelectionOption="true" 
                                  itemDisabled="true"/>
                    <f:selectItems id="cecase-add-origevent-selectitems"
                                   value="#{ceCaseAddBB.ceCaseOriginiationEventCandidateList}"
                                   var="ec" 
                                   itemValue="#{ec}" 
                                   itemLabel="#{ec.eventCategoryTitle}"/>
                </h:selectOneMenu>
            </div>

            <div class="p-col-4">
                <h:outputLabel value="Associated with unit?" />
            </div>
            <div class="p-col-8">

                <p:inputSwitch value="#{ceCaseAddBB.ceCaseUnitAssociated}"
                               onLabel="Yes"
                               offLabel="No">
                    <p:ajax update="cecase-unit-som" />
                </p:inputSwitch>

                <h:selectOneMenu id="cecase-unit-som"
                                 value="#{ceCaseAddBB.ceCaseUnitAssociation}"
                                 required="false"
                                 disabled="#{!ceCaseAddBB.ceCaseUnitAssociated}">

                    <f:converter converterId="propertyUnitConverter"/>
                    <f:selectItem itemLabel="select a unit on current property"
                                  noSelectionOption="true" 
                                  itemDisabled="true"/>
                    <f:selectItems id="cecase-unit-selectitems"
                                   value="#{systemServicesBB.bbSessionProperty.unitList}"
                                   var="pu" 
                                   itemValue="#{pu}" 
                                   itemLabel="#{pu.unitNumber} (ID:#{pu.unitID})"/>
                </h:selectOneMenu>
            </div>

          
        </div>

        <p:spacer height="5px" />

        <f:subview id="propprofile-caseadd-confirm"
                   rendered="#{cc.attrs.addfrompropertyprofile}" >
            <p:commandButton ajax="false" 
                             tabindex="5" 
                             icon="pi pi-folder-open"
                             value="Open Code Enforcement Case" 
                             action="#{ceCaseAddBB.onAddNewCaseCommitButtonChange}" 
                             rendered="#{ceCaseAddBB.permissionAllowCECaseCreate}"/>
        </f:subview>

        <f:subview id="finrouting-caseadd-confirm"
                   rendered="#{cc.attrs.addfromfinrouting}" >
            <p:commandButton ajax="false" 
                             tabindex="5" 
                             icon="pi pi-folder-open"
                             value="Open new case, assign inspection, and go to new case" 
                             action="#{fieldInspectionBB.completeRoutingStep4CreateNewCECase(null)}" 
                             rendered="#{ceCaseAddBB.permissionAllowCECaseCreate}"/>
        </f:subview>


    </cc:implementation>
</html>

src/main/webapp/resources/components/citationPenaltyTable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <cc:interface>
        <cc:attribute name="penaltylist" required="true" />
    </cc:interface>

    <cc:implementation>
        
        <f:subview id="penalty-header-subview"
                   rendered="#{not empty cc.attrs.penaltylist}">
            <h3>Violation penalties</h3>
        </f:subview>
        
        <p:dataTable    id="citation-penalties-table"
                        value="#{cc.attrs.penaltylist}"
                        rendered="#{not empty cc.attrs.penaltylist}"
                        var="penalty"  
                        rowKey="#{penality.penaltyID}"
                        tableStyleClass="primeDataTable"
                        draggableRows="false" 
                        tabindex="1">

            <p:column width="25%"
                      sortBy="#{penalty.penaltyType.label}">
                <f:facet name="header">
                    <h:outputText value="Type"/>
                </f:facet>
                <h:outputText value="#{penalty.penaltyType.label}" />
            </p:column>

            <p:column width="15%">
                <f:facet name="header">
                    <h:outputText value="Date"/>
                </f:facet>
                <h:outputText value="#{citationBB.getPrettyLocalDate(penalty.dateOfRecord)}" />
            </p:column>

            <p:column width="20%"
                      sortBy="#{penalty.fineAmount}">
                <f:facet name="header">
                    <h:outputText value="Amount"/>
                </f:facet>
                <h:outputText value="#{penalty.fineAmount}">
                    <f:convertNumber type="currency" currencySymbol="$" maxFractionDigits="2" />
                </h:outputText>

            </p:column>
            <p:column width="20%">
                <f:facet name="header">
                    <h:outputText value="Note"/>
                </f:facet>
                <div class="wrapText">
                    <h:outputText value="#{penalty.notes}" />
                </div>
            </p:column>

            <p:column width="10%">
                <f:facet name="header">
                    <h:outputText value="Actions"/>
                </f:facet>

                <div class="restrict-main-contents-io-link">
                    <p:commandLink      id="citation-penalty-edit-cb"
                                        ajax="true"
                                        actionListener="#{citationBB.onPenalityViewEdit(penalty)}"
                                        oncomplete="PF('citation-penalty-dialog-var').show()"
                                        rendered="#{citationBB.permissionAllowCitationUpdate}"
                                        update="citation-penalty-dialog"
                                        value="edit" />
                </div>
                <p:spacer height="3px" />
                <h:outputText value="(ID: #{penalty.penaltyID})" />
            </p:column>
        </p:dataTable>
    </cc:implementation>
</html>

src/main/webapp/resources/components/eventCalendarDisplay.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui" 
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:tt="http://xmlns.jcp.org/jsf/composite/components">
    <cc:interface>
        <cc:attribute name="value" required="true" />
    </cc:interface>

    <cc:implementation>
          <div class="evcal-evrow">
                                
            <div class="evcal-evicon-container">
                <i class="material-icons">
                    <h:outputText value="#{cc.attrs.value.category.icon.materialIcon}"/>
                </i>
            </div>
            <div class="evcal-evtime-container">
                <h:outputText value="#{sessionEventConductor.getPrettyTimeOnly(cc.attrs.value.timeStart)}" />
            </div>
            <div class="evcal-evcat-container"
                 style="font-size: 0.8em;">
                <div class="restrict-main-contents-io-link link-button"
                     style="padding-bottom: 0px;">
                    <p:commandLink id="evcal-event-open-button"
                                   styleClass="noFill button-size-small"
                                   style="padding-bottom: 0px;"
                                   value="#{cc.attrs.value.category.eventCategoryTitle}"
                                   oncomplete="PF('event-profile-dialog-var').show()"
                                   update="event-profile-dialog event-profile-form"
                                   actionListener="#{eventBB.onViewEvent(cc.attrs.value)}">
                         <f:param name="event-list-component-to-update" value="event-cal-form" />
                    </p:commandLink>
                </div>
                <f:subview id="event-followup-link-subview"
                           rendered="#{cc.attrs.value.followUpNeeded}">
                    <br />
                    <tt:eventFollowUpLink value="#{cc.attrs.value}"
                                          holder="#{null}"
                                          linktext="Follow up now" 
                                          updatecomponent="event-cal-form"/>
                </f:subview>
                <f:subview id="event-followup-notrequired-br"
                           rendered="#{not cc.attrs.value.followUpNeeded}">
                    <br />
                </f:subview>
                <p:commandLink id="evcal-holder-cl"
                               action="#{sessionEventConductor.onViewEventHolder(cc.attrs.value)}"
                               style="font-weight: bold; color:blue;">
                    <h:outputText value="#{cc.attrs.value.casePeriodPropertyString}"
                                  rendered="#{not empty cc.attrs.value.casePeriodPropertyString}"/>
                    <p:spacer height="1px" />
                    <h:outputText value="#{cc.attrs.value.parcelAddressOneLine}" escape="false" 
                                  rendered="#{not empty cc.attrs.value.parcelAddressOneLine}"/>
                </p:commandLink>
            </div>
        </div>
    </cc:implementation>
</html>

src/main/webapp/resources/components/permitFlowNavButtonBack.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <cc:interface>
        <cc:attribute name="previousstep" required="false" type="int"/>
    </cc:interface>

    <cc:implementation>
        <div class="gray_button">
            <p:commandButton
                id="permit-flow-back-button"
                value="Back to step #{cc.attrs.previousstep}: #{occPeriodBB.permitFlowStepMap[cc.attrs.previousstep]}"
                actionListener="#{occPeriodBB.gotoPermitFlowStepX}"
                ajax="true" 
                icon="pi pi-arrow-left"
                update="permit-steps-panel"
                rendered="#{cc.attrs.showback}">
                <f:param name="flowsteptarget" value="#{cc.attrs.previousstep}" />
            </p:commandButton>
        </div>
    </cc:implementation>
</html>